[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"
authors = ["Michael Fai√üt <michael@codenite.at>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
